name: RAG API CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # 1️⃣ Run Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/

  # 2️⃣ Build and Deploy
  build_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t ragapi:latest .

      - name: Save Docker image as tar
        run: docker save ragapi:latest -o ragapi.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "ragapi.tar"
          target: "~/ragapi.tar"

      - name: Load and run Docker on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Load Docker image
            docker load -i ~/ragapi.tar
            # Stop and remove old container if exists
            docker stop ragapi || true
            docker rm ragapi || true
            # Run new container
            docker run -d -p 8000:8000 --name ragapi ragapi:latest
            # Clean up tar file
            rm ~/ragapi.tar
