name: RAG API CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # 1️⃣ Run Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/

  # 2️⃣ Deploy to EC2 (build Docker on server)
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Copy entire project to EC2
      - name: Copy project to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "~/RAGAPI"

      # SSH into EC2, build Docker, and run container
      - name: Build and run Docker on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/RAGAPI
            docker build -t ragapi:latest .
            docker stop ragapi || true
            docker rm ragapi || true
            docker run -d -p 8000:8000 --name ragapi ragapi:latest
